### ISSUE TITLE
[Wed][20 Mar] Daily Issue Log

### ISSUE THREAD

**Issue by staceb** [staceb/reggie-and-stace-pairing#10]
**Skipped Halp Threads:**

https://github.zendesk.com/agent/tickets/109831

https://github.zendesk.com/agent/tickets/108972 (I think I might have worked the solution to this one).

https://github.zendesk.com/agent/tickets/108941

https://github.zendesk.com/agent/tickets/109117

**Today I Learned:**

Sometimes talking out the problem can help you to come to a solution faster. :-)

**I would also like to go over:**

~~https://github.zendesk.com/agent/tickets/106380~~

~~https://github.zendesk.com/agent/tickets/108067~~

~~https://github.zendesk.com/agent/tickets/106773~~

https://github.zendesk.com/agent/tickets/108746

https://github.zendesk.com/agent/tickets/108969

https://github.zendesk.com/agent/tickets/90435

https://github.zendesk.com/agent/tickets/94915 (off topic, but I am curious about this one.)

https://github.zendesk.com/agent/tickets/108938

https://github.zendesk.com/agent/tickets/109104 (I think I have the right answer on this one, only go over this one if no one gets to it by EOD)

https://github.zendesk.com/agent/tickets/109104 (attempted)

**Comment by staceb** [comment]
https://github.zendesk.com/agent/tickets/104072

**Comment by ReggieNora** [comment]
Went through this one today! Thanks @staceb!
